const movies = [
    {
        id: 1,
        title: '星际穿越',
        originalTitle: 'Interstellar',
        year: 2014,
        rating: 9.4,
        director: '克里斯托弗·诺兰',
        category: '科幻',
        duration: '169分钟',
        country: '美国 / 英国',
        poster: 'https://picsum.photos/seed/interstellar/400/600',
        banner: 'https://picsum.photos/seed/interstellar-banner/900/400',
        desc: '在地球资源逐渐枯竭的未来，前NASA宇航员库珀被选中参加一项穿越虫洞的星际任务，为人类寻找新的家园。诺兰以严谨的科学态度与宏大的视觉奇观，呈现了一部关于爱与时间的太空史诗。',
        tags: ['太空', '时间旅行', '亲情', '硬科幻'],
        highlight: { 'IMDb': '8.7', '豆瓣': '9.4', '奥斯卡': '最佳视觉效果' },
        watchUrl: 'https://www.iqiyi.com/v_19rrn6k5qw.html',
        trailerUrl: 'https://www.bilibili.com/video/BV1Rs411y7zD'
    },
    {
        id: 2,
        title: '肖申克的救赎',
        originalTitle: 'The Shawshank Redemption',
        year: 1994,
        rating: 9.7,
        director: '弗兰克·德拉邦特',
        category: '剧情',
        duration: '142分钟',
        country: '美国',
        poster: 'https://picsum.photos/seed/shawshank/400/600',
        banner: 'https://picsum.photos/seed/shawshank-banner/900/400',
        desc: '银行家安迪因被误判谋杀妻子而关进肖申克监狱。在漫长的牢狱生涯中，他用智慧与毅力赢得了尊重，也悄然筹划着惊天越狱。影片深刻探讨了希望、自由与救赎的力量。',
        tags: ['监狱', '希望', '友情', '经典'],
        highlight: { 'IMDb': '9.3', '豆瓣': '9.7', '地位': '影史TOP1' },
        watchUrl: 'https://v.qq.com/x/cover/3s7g6u7t8p9q0r1.html',
        trailerUrl: ''
    },
    {
        id: 3,
        title: '你的名字。',
        originalTitle: '君の名は。',
        year: 2016,
        rating: 8.8,
        director: '新海诚',
        category: '动画',
        duration: '106分钟',
        country: '日本',
        poster: 'https://picsum.photos/seed/yourname/400/600',
        banner: 'https://picsum.photos/seed/yourname-banner/900/400',
        desc: '生活在乡下的三叶与东京高中生泷，在某天醒来后发现自己与对方互换了身体。新海诚用绝美画面讲述了一段跨越时空的纯爱故事。',
        tags: ['纯爱', '时空', '青春', '催泪'],
        highlight: { '豆瓣': '8.8', '票房': '全球3.6亿美元', '导演': '新海诚代表作' },
        watchUrl: 'https://www.bilibili.com/bangumi/play/ep267851',
        trailerUrl: ''
    },
    {
        id: 4,
        title: '盗梦空间',
        originalTitle: 'Inception',
        year: 2010,
        rating: 9.3,
        director: '克里斯托弗·诺兰',
        category: '科幻',
        duration: '148分钟',
        country: '美国 / 英国',
        poster: 'https://picsum.photos/seed/inception/400/600',
        banner: 'https://picsum.photos/seed/inception-banner/900/400',
        desc: '道姆·柯布是一名技艺高超的"盗梦者"，能够潜入他人梦境窃取机密。层层嵌套的梦境、令人窒息的悬念，诺兰再次挑战观众的大脑极限。',
        tags: ['梦境', '悬疑', '动作', '烧脑'],
        highlight: { 'IMDb': '8.8', '豆瓣': '9.3', '奥斯卡': '4项大奖' },
        watchUrl: 'https://v.qq.com/x/cover/1q2w3e4r5t6y7u8.html',
        trailerUrl: ''
    },
    {
        id: 5,
        title: '泰坦尼克号',
        originalTitle: 'Titanic',
        year: 1997,
        rating: 9.1,
        director: '詹姆斯·卡梅隆',
        category: '爱情',
        duration: '194分钟',
        country: '美国',
        poster: 'https://picsum.photos/seed/titanic/400/600',
        banner: 'https://picsum.photos/seed/titanic-banner/900/400',
        desc: '1912年，穷画家杰克与贵族少女露丝在泰坦尼克号上相遇相恋。这段跨越阶级的爱情故事成为影史永恒的经典。',
        tags: ['灾难', '浪漫', '经典', '史诗'],
        highlight: { 'IMDb': '7.9', '豆瓣': '9.1', '奥斯卡': '11项大奖' },
        watchUrl: 'https://www.iqiyi.com/v_19rrn6k5qw.html',
        trailerUrl: ''
    },
    {
        id: 6,
        title: '疯狂动物城',
        originalTitle: 'Zootopia',
        year: 2016,
        rating: 8.9,
        director: '拜伦·霍华德 / 瑞奇·摩尔',
        category: '动画',
        duration: '109分钟',
        country: '美国',
        poster: 'https://picsum.photos/seed/zootopia/400/600',
        banner: 'https://picsum.photos/seed/zootopia-banner/900/400',
        desc: '小兔子朱迪实现了当警察的梦想，与狐狸尼克搭档破获了一桩神秘案件。迪士尼用欢乐动画传递深刻社会议题。',
        tags: ['冒险', '喜剧', '社会', '迪士尼'],
        highlight: { '豆瓣': '8.9', '奥斯卡': '最佳动画长片', '票房': '全球10亿美元' },
        watchUrl: 'https://v.qq.com/x/cover/9o8i7u6y5t4r3e2.html',
        trailerUrl: ''
    },
    {
        id: 7,
        title: '看不见的客人',
        originalTitle: 'Contratiempo',
        year: 2016,
        rating: 9.0,
        director: '奥里奥尔·保罗',
        category: '悬疑',
        duration: '106分钟',
        country: '西班牙',
        poster: 'https://picsum.photos/seed/contratiempo/400/600',
        banner: 'https://picsum.photos/seed/contratiempo-banner/900/400',
        desc: '成功企业家阿德里安被指控谋杀情人，在开庭前夜的对话中，真相与谎言层层交织。西班牙悬疑片的巅峰之作。',
        tags: ['反转', '犯罪', '推理', '西班牙'],
        highlight: { '豆瓣': '9.0', 'IMDb': '8.1', '口碑': '悬疑神作' },
        watchUrl: 'https://www.iqiyi.com/v_19rrn6k5qw.html',
        trailerUrl: ''
    },
    {
        id: 8,
        title: '谍影重重',
        originalTitle: 'The Bourne Identity',
        year: 2002,
        rating: 8.6,
        director: '道格·里曼',
        category: '动作',
        duration: '119分钟',
        country: '美国 / 德国',
        poster: 'https://picsum.photos/seed/bourne/400/600',
        banner: 'https://picsum.photos/seed/bourne-banner/900/400',
        desc: '一名失忆的男子被渔民从海中救起，在追寻身份的过程中发现自己拥有惊人的格斗技能。重新定义了现代间谍动作片的标杆。',
        tags: ['间谍', '失忆', '追车', '近身格斗'],
        highlight: { 'IMDb': '7.9', '豆瓣': '8.6', '系列': '五部曲开篇' },
        watchUrl: '',
        trailerUrl: ''
    },
    {
        id: 9,
        title: '楚门的世界',
        originalTitle: 'The Truman Show',
        year: 1998,
        rating: 9.2,
        director: '彼得·威尔',
        category: '剧情',
        duration: '103分钟',
        country: '美国',
        poster: 'https://picsum.photos/seed/truman/400/600',
        banner: 'https://picsum.photos/seed/truman-banner/900/400',
        desc: '楚门从出生起就生活在一个巨大的摄影棚中，当他决心冲破虚假的牢笼时，全世界都在注视着他。对媒体时代的深刻寓言。',
        tags: ['讽刺', '自由', '媒体', '经典'],
        highlight: { 'IMDb': '8.2', '豆瓣': '9.2', '意义': '媒体批判经典' },
        watchUrl: 'https://v.qq.com/x/cover/5t4r3e2w1q0o9i8.html',
        trailerUrl: ''
    },
    {
        id: 10,
        title: '功夫',
        originalTitle: 'Kung Fu Hustle',
        year: 2004,
        rating: 8.8,
        director: '周星驰',
        category: '喜剧',
        duration: '99分钟',
        country: '中国香港',
        poster: 'https://picsum.photos/seed/kungfuhustle/400/600',
        banner: 'https://picsum.photos/seed/kungfuhustle-banner/900/400',
        desc: '小混混阿星误闯猪笼城寨，意外卷入了斧头帮与隐藏高手之间的对决。周星驰将无厘头喜剧与功夫元素完美融合。',
        tags: ['功夫', '无厘头', '周星驰', '华语经典'],
        highlight: { '豆瓣': '8.8', 'IMDb': '7.7', '金像奖': '最佳影片' },
        watchUrl: 'https://www.iqiyi.com/v_19rrn6k5qw.html',
        trailerUrl: ''
    },
    {
        id: 11,
        title: '千与千寻',
        originalTitle: '千と千尋の神隠し',
        year: 2001,
        rating: 9.4,
        director: '宫崎骏',
        category: '动画',
        duration: '125分钟',
        country: '日本',
        poster: 'https://picsum.photos/seed/spiritedaway/400/600',
        banner: 'https://picsum.photos/seed/spiritedaway-banner/900/400',
        desc: '少女千寻误入神灵世界，为了拯救变成猪的父母，在汤屋中经历了成长与勇气的考验。宫崎骏的巅峰之作。',
        tags: ['奇幻', '成长', '宫崎骏', '奥斯卡'],
        highlight: { '豆瓣': '9.4', '奥斯卡': '最佳动画长片', '票房': '日本影史冠军' },
        watchUrl: 'https://www.bilibili.com/bangumi/play/ep90876',
        trailerUrl: ''
    },
    {
        id: 12,
        title: '爱乐之城',
        originalTitle: 'La La Land',
        year: 2016,
        rating: 8.4,
        director: '达米恩·查泽雷',
        category: '爱情',
        duration: '128分钟',
        country: '美国',
        poster: 'https://picsum.photos/seed/lalaland/400/600',
        banner: 'https://picsum.photos/seed/lalaland-banner/900/400',
        desc: '爵士钢琴家塞巴斯蒂安与怀揣演员梦的米娅在洛杉矶相遇相恋，追梦路上彼此鼓励，也面临现实与理想的抉择。',
        tags: ['歌舞', '梦想', '浪漫', '奥斯卡'],
        highlight: { '豆瓣': '8.4', '奥斯卡': '6项大奖', '配乐': '经典原声' },
        watchUrl: 'https://v.qq.com/x/cover/8u7y6t5r4e3w2q1.html',
        trailerUrl: ''
    },
    {
        id: 13,
        title: '搏击俱乐部',
        originalTitle: 'Fight Club',
        year: 1999,
        rating: 9.0,
        director: '大卫·芬奇',
        category: '悬疑',
        duration: '139分钟',
        country: '美国',
        poster: 'https://picsum.photos/seed/fightclub/400/600',
        banner: 'https://picsum.photos/seed/fightclub-banner/900/400',
        desc: '一个饱受失眠折磨的白领遇到了肥皂商人泰勒，两人创立了一个秘密的地下搏击俱乐部。大卫·芬奇的cult经典。',
        tags: ['心理', '反转', 'cult', '大卫·芬奇'],
        highlight: { 'IMDb': '8.8', '豆瓣': '9.0', '风格': 'Cult经典' },
        watchUrl: 'https://www.iqiyi.com/v_19rrn6k5qw.html',
        trailerUrl: ''
    },
    {
        id: 14,
        title: '速度与激情7',
        originalTitle: 'Furious 7',
        year: 2015,
        rating: 8.0,
        director: '温子仁',
        category: '动作',
        duration: '137分钟',
        country: '美国',
        poster: 'https://picsum.photos/seed/furious7/400/600',
        banner: 'https://picsum.photos/seed/furious7-banner/900/400',
        desc: '多米尼克一家面临最危险的对手，从阿布扎比摩天大楼间的飞车到洛杉矶街头的决战。片尾对保罗·沃克的致敬让无数观众泪目。',
        tags: ['赛车', '动作', '情怀', '保罗·沃克'],
        highlight: { '豆瓣': '8.0', '票房': '全球15亿美元', '主题曲': 'See You Again' },
        watchUrl: 'https://v.qq.com/x/cover/1a2b3c4d5e6f7g8h.html',
        trailerUrl: ''
    },
    {
        id: 15,
        title: '让子弹飞',
        originalTitle: 'Let the Bullets Fly',
        year: 2010,
        rating: 9.0,
        director: '姜文',
        category: '剧情',
        duration: '132分钟',
        country: '中国大陆',
        poster: 'https://picsum.photos/seed/letbulletsfly/400/600',
        banner: 'https://picsum.photos/seed/letbulletsfly-banner/900/400',
        desc: '悍匪张牧之劫了马拉火车，冒充县长赴鹅城上任，与恶霸黄四郎展开斗智斗勇的较量。姜文用黑色幽默拍出了一部华语神作。',
        tags: ['黑色幽默', '西部', '姜文', '华语神作'],
        highlight: { '豆瓣': '9.0', '台词': '经典无数', '风格': '站着把钱挣了' },
        watchUrl: 'https://www.iqiyi.com/v_19rrn6k5qw.html',
        trailerUrl: ''
    }
];